# Generated by Django 4.0.1 on 2022-01-08 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesforce_user_id', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('token', models.CharField(blank=True, max_length=256, null=True)),
                ('security_token', models.CharField(max_length=256)),
                ('active', models.BooleanField(db_index=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salesforce_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
